octomap/src/graph2tree.cpp
In some cases I have the robot position and the scan points already expressed in the global frame.
In this scenario it is much effort to make change my scan graph to be "relative" rather than skipping the transformation part in graph2tree (commit adds only 5 lines of code in octomap/src/graph2tree.cpp).
=> add a flag (-g) to graph2tree to indicate that the nodes are already transformed in global coordinates

octomap/include/octomap/OccupancyOcTreeBase.h
This is a small pull request with some small changes to enable sending diffs of an Octomap instead of the whole tree in Moveit.
=> Small additions to change detection for sending Octomap diffs

octomap/include/octomap/OcTreeBaseImpl.h, octomap/include/octomap/OcTreeBaseImpl.hxx
Hello,
I have updated the `OcTree::getUnknownLeafCenters` function so that now you can find unknown voxel centers and a given tree depth.
One minor issue I am not completely sure about is whether the result of `pow` has to be explicitly cast to `float` [here](https://github.com/OctoMap/octomap/compare/devel...aecins:devel#diff-0ca930832184b7ca8ee05bda43a61353R867).
Cheers,
Alex
=> Updated getUnknownLeafCenters to have tree depth as a parameter

octomap/include/octomap/OcTreeBaseImpl.h
Remove needless forward declare that were defined after the implementation had already been included, causing warnings when compiling with -Wredeclared-class-member.
This occurs when doing:
```c++
struct A { struct B{}; struct B; };
```
=> Fix -Wredeclared-class-member warnings

octomap/include/octomap/ColorOcTree.h, octomap/include/octomap/CountingOcTree.h, octomap/include/octomap/OcTree.h, octomap/include/octomap/OcTreeStamped.h, octomap/src/ColorOcTree.cpp, octomap/src/CountingOcTree.cpp, octomap/src/OcTree.cpp, octomap/src/OcTreeStamped.cpp, octomap/src/testing/test_io.cpp
Explicitly calling a dummy function from c'tor ensures that MSVC does
not optimize the StaticMemberInitializer away. Extended and verified
test_io to read / write OcTree, ColorOcTree and OcTreeStamped.
=> Proposed fixes for IO factory class registry with MSVC (#51)

octovis/include/octovis/CameraFollowMode.h, octovis/include/octovis/SceneObject.h, octovis/include/octovis/ViewerSettingsPanel.h, octovis/src/OcTreeDrawer.cpp
Some octovis headers include qglviewer.h unnecessarily.  By removing
the header dependency it is easier to include octovis headers without
requiring an include path for qglviewer.
This commit could break user code that relies on the header, but those
compile errors will be easy to fix.
=> remove qglviewer.h header dependency from some public headers

dynamicEDT3D/include/dynamicEDT3D/dynamicEDTOctomap.h, dynamicEDT3D/include/dynamicEDT3D/dynamicEDTOctomap.hxx, dynamicEDT3D/src/CMakeLists.txt, dynamicEDT3D/src/examples/CMakeLists.txt, dynamicEDT3D/src/examples/exampleEDTOctomap.cpp, dynamicEDT3D/src/examples/exampleEDTOctomapStamped.cpp
This PR allows to use dynamicEDT3D with any type of OcTree. For now, only OctomapStamped has been tested. It is done in a way such that it is compatible with current API.
@gauthamm FYI.
=> Templated dynamicEDT3D

octomap/include/octomap/OcTreeKey.h
I am using a std::map keyed on OcTreeKeys to represent a costmap over Octomap nodes. It uses a Compare object that uses `OcTreeKey::KeyHash`. When debugging a program with Clang Undefined Behavior Sanitizer, I got the following error.
```
/usr/include/octomap/OcTreeKey.h:100:49: runtime error: signed integer overflow: 345637 * 32767 cannot be represented in type 'int'
```
It seems that the cast to size_t in this function doesn't quite work. Using C++-style `static_cast` fixes the issue. I believe that `(size_t) key.k[0]` would also work, but `static_cast` will give compile-type checking ability.
=> use static_cast in KeyHash

dynamicEDT3D/dynamicEDT3DConfig.cmake.in, octomap/octomap-config.cmake.in, octovis/octovis-config.cmake.in
The presence of `*-config-version.cmake` files not withstanding, it is common to include version information in `*-config.cmake` files for ease of use by downstream projects.
=> Add version information to *-config.cmake files

octovis/include/octovis/ViewerGui.h, octovis/include/octovis/ViewerSettingsPanel.h, octovis/src/ViewerGui.cpp, octovis/src/ViewerSettingsPanel.cpp, octovis/src/main.cpp
Just a convenience commit for octovis:
My laptop is too slow to display big maps smoothly.
So on startup I like to have a coarser view, move the map in a desired 
position and then increase the cutoff to view that perspective in detail,
make screenshots and whatsoever.
Also shows a short usage message if started without parameters.
=> Command line param for the initial tree depth cutoff

octovis/include/octovis/OcTreeDrawer.h, octovis/include/octovis/ViewerGui.h, octovis/include/octovis/ViewerGui.ui, octovis/src/OcTreeDrawer.cpp, octovis/src/ViewerGui.cpp
Replacement for PR #136. See extended description there.
By using opengl compiled display lists for rendering
the cubes, CPU and RAM usage and CPU-GPU communication
can be strongly reduced, leading to 3-4x higher frame
rates at half the CPU and RAM usage.
The drawbacks are long "compilation" times before the
first rendering and upon all changes in the octree
display, like selecting a new colormap or depth cutoff
(but not on changing the perspective of course).
Further, for displaying too detailed maps octovis may crash,
supposably due to exhaustion of the RAM on the graphics card.
Therefore the feature is off by default, but can be enabled
by checking View->"Alternate Rendering"
=> Add alternative rendering method

octomap/include/octomap/OcTreeBaseImpl.hxx
Makes `getUnknownLeafCenters` return true leaf centers. Fixes #146.
=> Fix getUnknownLeafCenters to return true leaf centers

octovis/CMakeLists.txt
I ran into a problem of building octomap from source with a locally installed "ros-kinetic-octovis" package. The compiler was wrongly using the incompatible header installed in my system instead of the header shipped with the sources. My change resolves this issue on my system, thus you might want to take over this small change.
=> Improved build by specifically targeting local includes in case of available system includes

octovis/src/ViewerGui.cpp
a minimal workaround for the ColorOcTree type register issue on the visual studio 2012 platform of windows 8
a redundant object definition to ensure VS2012 not to drop the the constructor of the member static class called StaticMemberInitializer, causing the ColorOcTree failing to register.
=> a minimal workaround for the register issue

octomap/src/CountingOcTree.cpp
This seems a critical bug, and I can't find any code which works with CountingOcTree,
there is no example code.
Checking if root is NULL is necessary, and this PR fixes the issue by creating root node if it does not exist.
=> Fix segv of CountingOcTree by checking root == NULL

octomap/src/CMakeLists.txt
The title says it all: building `octomap-static` **should** also build its dependency `octomath-static`.
No need to manually call `add_dependencies()` for their shared lib versions because CMake automatically adds the dependency because one is linked against the other.
=> Fix octomap-static dependency on octomath-static

CMakeLists.txt
This is to prevent errors like this one, while linking liboctomath.a against another user shared library:
```
/usr/bin/ld: ../../lib/liboctomath.a(Vector3.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
../../lib/liboctomath.a: error adding symbols: Bad value
```
=> Enable -fPIC in gcc/clang

octomap/include/octomap/OcTreeBaseImpl.hxx
This PR adds `typename` keyword to dependent type names. [Here](https://stackoverflow.com/a/613132/3122234) is a reference for why `typename` keyword is necessary. This patch is to fix the [build failures on Windows](https://ci.appveyor.com/project/jslee02/dart/build/5522/job/8r6c3sfjb05u5t22#L1454).
Caveat: I haven't built Octomap on Windows with this patch because I don't have a Windows machine currently so there could be other issues.
=> Add missing typename keyword

octomap/include/octomap/MapNode.hxx, octomap/include/octomap/OcTreeBaseImpl.hxx, octomap/include/octomap/OcTreeIterator.hxx, octomap/include/octomap/OcTreeStamped.h, octomap/include/octomap/OccupancyOcTreeBase.hxx, octomap/src/ColorOcTree.cpp, octomap/src/CountingOcTree.cpp, octomap/src/OcTree.cpp, octomap/src/OcTreeStamped.cpp, octomap/src/binvox2bt.cpp, octovis/src/OcTreeDrawer.cpp, octovis/src/extern/QGLViewer/quaternion.h
That's it... tested with gcc 7.2, this patch avoids tons of warnings related to shadowed local variables and members.
All tests pass.
PS: Yes, `-Wshadow` may be quite a pedantic flag, but I think shadowing is a think to avoid ;-) At the very least, the ambiguity can be confusing to a reader.
=> fix all gcc -Wshadow warnings in public headers

octomap/src/Pointcloud.cpp
In particular, `std::random_shuffle` is removed from C++17 and above, so octomap will not compile.
=> Do not use std::random_shuffle with C++11 or above

octomap/src/binvox2bt.cpp, octomap/src/edit_octree.cpp
byte is defined in <cstddef> since C++17
=> c++: fix issue with byte typedef when compiling using C++17

dynamicEDT3D/package.xml, octomap/package.xml, octovis/package.xml
- We don't need to specify a catkin dependency (and it fails to resolve on ROS2). 
- Required for #237 
- I plan to make a 1.9.1 release using these changes and the 16 commits between 1.9.0 and the current devel
=> Update package.xml to remove catkin dependency

octomap/include/octomap/OccupancyOcTreeBase.hxx
`OccupancyOcTreeBase<NODE>::insertPointCloudRays` has an unused parameter!
To silence compiler warnings `-Wunused-parameter`, I commented the parameter name.
=> fix unused-parameter warning

octovis/package.xml
octovis is currently failing on the ROS Melodic and Dashing buildfarms because my previous PR accidentally omitted a required dependency (and that the fallback builds libqlviewer-qt4 in the source tree).
This PR:
- Fixes the missing dependency in octovis' package.xml (and also changes the style back to build and exec dependencies)
- Also changes the generation of CMake config files etc. to happen in the binary dir instead of in the source directory. This is required on read-only filesystems
- Adds the public link attribute for octovis
@ahornung, could you please make a patch release 1.9.2 after this PR? Thank you :-)
=> Fix ROS Melodic/Dashing buildfarm failures

octomap/src/math/CMakeLists.txt
The `INSTALL_NAME_DIR` interfered with CMake's install process. With it in place, linkage looked like this:
```
$ otool -L /usr/local/lib/liboctomap.1.9.0.dylib 
/usr/local/lib/liboctomap.1.9.0.dylib:
@rpath/liboctomap.1.9.dylib (compatibility version 1.9.0, current version 1.9.0)
/Users/bo/Downloads/octomap-1.9.0/octomap/lib/liboctomath.1.9.dylib (compatibility version 1.9.0, current version 1.9.0)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```
This clearly doesn't look right - it has references the build directory rather than the install directory.
Upon removing `INSTALL_NAME_DIR`, we get the much better looking:
```
$ otool -L /usr/local/lib/liboctomap.1.9.0.dylib …
```
=> Removed problematic INSTALL_NAME_DIR

octomap/include/octomap/AbstractOccupancyOcTree.h, octomap/include/octomap/OcTreeKey.h
As requested in #273, this PR targets `devel` branch, and intends to fix the `-Wpedantic` warnings shown up when compiling moveit2 against the release version of octomap: `ros-dashing-octomap`. These warnings block the CI of moveit2. Please see [here](https://travis-ci.org/ros-planning/moveit2/jobs/628989417#L988).
=> Fix -Wpedantic warnings

.travis.yml, CMakeLists.txt, octovis/CMakeLists.txt, octovis/CMakeModules/FindQGLViewer.cmake
Hi,
PR #238 seems to be stuck, so this one has the same CMake changes but does not touch ROS files while enabling Travis to build with Qt5.
=> Qt5 and travis

dynamicEDT3D/CMakeLists.txt, dynamicEDT3D/CMakeModules/InstallPkgConfigFile.cmake, dynamicEDT3D/src/CMakeLists.txt, octomap/CMakeLists.txt, octomap/CMakeModules/InstallPkgConfigFile.cmake, octomap/src/CMakeLists.txt, octomap/src/math/CMakeLists.txt, octovis/CMakeLists.txt, octovis/CMakeLists_src.txt
Still defaults to PREFIX/lib but e.g. Debian or Fedora packagers
can easily set it to lib/x86_64-linux-gnu or lib64 respectively.
=> Support configurable libdir

octovis/package.xml
Recently, OCTOVIS_QT5 was set to ON by default (cf. #280). This requires updated package dependencies to work on the buildfarm. I am unclear if this will fully work or if we first need to upstream `libqglviewer-qt5` as a rosdep key, and then also add it to `octovis`. With a local `industrial_ci` build, this appeared to work though.
=> [octovis] Update dependencies to Qt5

octomap/src/binvox2bt.cpp, octomap/src/edit_octree.cpp
std::byte can't be read from a file (no overload of operator >>
available), fall back to typedef'fing it to unsigned char again.
Related: #240
=> fix ifstream >> byte with c++17

octovis/CMakeModules/CompilerSettings.cmake
Currently, `-fPIC` is only set for GCC. This results in compiler errors when using a different compiler (clang in my case).
=> octovis: use -fPIC with all compilers

octovis/CMakeModules/FindQGLViewer.cmake
just a small fix. There was already an if-else to check if qmake-qt4 is available, but the call in else was still using qmake-qt4 even if not available.
=> fix qmake command to build libQGLViewer with Qt5.

.github/workflows/industrial_ci_action.yml
Adds an additional CI using GitHub Actions based on the ROS-Industrial CI. It's configured to run the prerelease checks by default. This can help spot issues for releasing OctoMap into the different ROS distros.
Example build: https://github.com/wxmerkt/octomap/runs/1717836573
=> Add GitHub Actions CI based on ROS-Industrial CI

octomap/include/octomap/OcTreeBaseImpl.hxx, octomap/include/octomap/OccupancyOcTreeBase.hxx
Using explicit casting fixes compiler warnings
=> Use explicit casting to prevent implicit sign conversion

.github/workflows/industrial_ci_action.yml, dynamicEDT3D/CMakeLists.txt, dynamicEDT3D/package.xml, octomap/CMakeLists.txt, octomap/package.xml, octovis/CMakeLists.txt, octovis/package.xml
In this PR, an exec_dependency on either `catkin` or `ament_cmake` is added per REP-136. The package format is updated to v3 to make use of `condition` arguments. This allows to only maintain a single `devel` branch and effectively deprecate `ros2` going forward. ROS1 and ROS2 can now use `devel`.
@ruffsl @mikaelarguedas can you please test if this works for you?
Alternative to #303
=> REP-136 compliance and compatibility with ROS1 & ROS2 using single branch

octovis/CMakeLists_src.txt, octovis/include/octovis/ViewerGui.h, octovis/include/octovis/ViewerWidget.h, octovis/src/OcTreeDrawer.cpp, octovis/src/ViewerGui.cpp
This PR closes the following issues:
#337 : by commits 92e39d7 and dd885fd
#338 : by commits: be87f58 and 9c73561 
The volume selection feature (selection is triggered with Shift+LClick in the viewer) adds the following UI changes:
- New panel in the octovis status bar showing the center coordinates of the last selected voxel ("--,--,--" when selecting empty space).
- Highlighting of the selected volume in 255red with alpha=1 (alpha is usually 0.8 in occupied volumes, so it is visually recognisable even if the occupied volume has the same color as the selected volume).
The changes can be seen in the below before/after figures.
**Before:**
**After (with a voxel selected):**
Let me know if you'd like to separate the PR into multiple ones covering singular issues or anything else I can do to …
=> octovis: Implement volume selection features

dynamicEDT3D/package.xml, octomap/package.xml, octovis/package.xml
REP-136 recommends that third-party (non-ROS) packages add a runtime
dependency on catkin so that the setup scripts provided by the catkin
package which set up a ROS environment are installed along with that
package. In ROS 2, those scripts are provided by the ros_workspace
package and bloom transparently injects a dependency on ros_workspace
into every released package.
It would be possible to use ament_cmake (or more likely the individual
ament_cmake_core package to optionally provide the package.xml and
ament resource index registration but since what you have is working
fine I think just removing the unecessary dependency is a good next
step. As mentioned in
https://github.com/flexible-collision-library/fcl/pull/536#issuecomment-845533649
we haven't produced a definitive …
=> Remove unused ament_cmake dependency.

octomap/include/octomap/OccupancyOcTreeBase.h, octomap/include/octomap/OccupancyOcTreeBase.hxx
otherwise passing temporaries does not work.
Found it while writing code for MoveIt's octomap plugin.
=> make setBBXMin/Max parameters const

octomap/include/octomap/OccupancyOcTreeBase.hxx, octomap/src/testing/CMakeLists.txt, octomap/src/testing/test_bbx.cpp, octomap/src/testing/testing.h
This pull request addresses #358. If the bounding box is set and the scan point is within the bounding box and within the max range (if set), then the cell containing the the scan point is added to occupied cells. Now, even if the scan point is outside the bounding box or beyond the max range, cells will be added to the free cells set. The end point is truncated to stop at the max range if the original scan point is beyond max range. Then, we iterate through the key ray and add cells to the free_cells list, breaking when we leave the bounding box.
=> Bug fix to update freespace when bbx is set.

octomap/src/binvox2bt.cpp
This PR intends to fix overflow problem in binvox2bt.cpp. The conversion failed when the result of operation  _width * height * depth_ (i.e., number of voxels) was higher than the size of int.
=> fixed overflow problem in binvox2bt

octomap/octomap-config.cmake.in
Relates to https://github.com/OctoMap/octomap/issues/138
We have seen issues where OctoMap did not get configured properly due to common use of `find_package(octomap REQUIRED)` in downstream packages (i.e. lower-case octomap). This issue has become more common on ROS2 and previously was circumvented by a patch to change the LIBDIR. Defining both variables grandfathers in downstream users (including using ament-auto-configure) by also providing the required configuration variables with a lower-case as in the project name.
=> Also set lowercase octomap_* variables in CMake config

octomap/include/octomap/OcTreeIterator.hxx
Solves #372 
Based on reading following helpful source: https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/
With this build error resolved, octomap is cxx17 compat.
=> replace deprecated std::iterator by defining required types

octomap/src/testing/CMakeLists.txt
Hi,
Running tests with `CTEST_PARALLEL_LEVEL` > 1, I get the following error:
```
3/14 Test  #5: ReadGraph ........................***Failed    0.00 sec
ERROR: Filestream to test.graph not open, nothing read.
test failed (EXPECT_TRUE) in octomap/src/testing/unit_tests.cpp, line 154
```
So I guess we need to explain to CMake that `ReadGraph` must wait for `InsertScan`, ref:
https://github.com/OctoMap/octomap/blob/b7118e096abb223fe3ce2af70e6f8c751989fe1d/octomap/src/testing/unit_tests.cpp#L147
=> fix test dependencies

octomap/include/octomap/ScanGraph.h
This fixes the following error on latest msvc compiler:
error C2666: 'octomap::ScanNode::operator ==': overloaded functions have similar conversions
message : could be 'bool octomap::ScanNode::operator ==(const octomap::ScanNode &)'
message : or 'bool octomap::ScanNode::operator ==(const octomap::ScanNode &)' [synthesized expression 'y == x']
message : while trying to match the argument list '(octomap::ScanNode, octomap::ScanNode)'
=> ScanGraph.h - fix c++20 compilation error

octovis/package.xml
It appears that libGLU is an indirect dependency on Ubuntu, but not on RHEL/Fedora. Better to be explicit anyway.
Here's the rosdep key: https://github.com/ros/rosdistro/blob/f4e07369c9790cd890a4cb34c001c94e8d4aad69/rosdep/base.yaml#L6943C1-L6958
Here's where openGL is found: https://github.com/OctoMap/octomap/blob/312f6b072c379489e2c00307bb35f8e7a851bed7/octovis/CMakeLists.txt#L71
Here's where both libGL and libGLU are referenced: https://github.com/OctoMap/octomap/blob/312f6b072c379489e2c00307bb35f8e7a851bed7/octovis/CMakeLists_src.txt#L104-L105
This is why `octovis` is [blocked](https://github.com/ros2/ros_buildfarm_config/blob/70e06f3ba7670bc030148893c40405b0092347d6/rolling/release-rhel-build.yaml#L33) on the ROS 2 buildfarm for RHEL.
=> Declare missing octovis dependency on opengl
